### ISSUE TITLE
this is not well written

### ISSUE THREAD

**Issue by georgelgore** [learn-co-curriculum/mod3-project-week-setup-example#1]
this is somewhere between code along and a reading. It doesn't achieve either. If you follow this as if it were a code along you're missing things. It's WAY too long to be a reading.

**Comment by DanielSeehausen** [comment]
Hi there,

Thank you for opening the issue. After reviewing with the team:

While unlike most other READMEs/labs/code-alongs, this has been designed to be a longer form code-along. Appreciating that it requires more endurance, the team believes there are some lessons that require a longer format to communicate a single full picture.  

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
